version: '3'

services:
  
  loadbalancer:
    image: loadbalancer
    container_name: loadbalancer
    environment:
      - APP=loadbalancer
    ports:
      - "8080:5000"
    

  cat1:
    image: server
    container_name: cat1
    environment:
      - APP=cat  

  cat2:
    image: server
    container_name: cat2
    environment:
      - APP=cat

  cat3:
    image: server
    container_name: cat3
    environment:
      - APP=cat  
    
  dog1:
    image: server
    container_name: dog1
    environment:
      - APP=dog

  dog2:
    image: server
    container_name: dog2
    environment:
      - APP=dog
  
  dog3:
    image: server
    container_name: dog3
    environment:
      - APP=dog

  mouse1:
    image: server
    container_name: mouse1
    environment:
      - APP=mouse
    
  mouse2:
    image: server
    container_name: mouse2
    environment:
      - APP=mouse
    
  fish1:
    image: server
    container_name: fish1
    environment:
      - APP=fish
    
  fish2:
    image: server
    container_name: fish2
    environment:
      - APP=fish
